ShowSprites:            true
ScriptEditor:           null
Translucency:           50
Language:               null
CreateBackups:          true
MapSortOrder:           1
HexPrefix:              0x
ShowRawMapHeader:       false
ShowRawLayoutHeader:    false
