ShowSprites:            true
ScriptEditor:           Test
Translucency:           50
Language:               Test
CreateBackups:          true
MapSortOrder:           0
HexPrefix:              0x
ShowRawMapHeader:       false
ShowRawLayoutHeader:    false
